repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v1.5.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
  - id: pretty-format-toml
    args: [--autofix]

- repo: https://github.com/PyCQA/isort
  rev: 5.6.4
  hooks:
  - id: isort
    args: [--profile, black]

- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.7.1
  hooks:
  - id: prettier
    types_or: [css, ts, tsx, javascript]
